
export const popularSkills = [
  // Web Development
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Python",
  "Django",
  "Flask",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "WordPress",
  "Java",
  "Spring",
  "C#",
  ".NET",
  "Go",
  "Rust",
  "GraphQL",
  "REST APIs",
  "WebSockets",
  "Webpack",
  "Vite",
  "Tailwind CSS",
  "Bootstrap",
  "Sass/SCSS",
  "WebAssembly",

  // Mobile Development
  "iOS Development",
  "Swift",
  "SwiftUI",
  "Objective-C",
  "Android Development",
  "Kotlin",
  "Jetpack Compose",
  "React Native",
  "Flutter",
  "Dart",
  "Xamarin",
  "Ionic",

  // Blockchain & Web3
  "Solidity",
  "Hardhat",
  "Truffle",
  "Ethers.js",
  "Web3.js",
  "Polygon",
  "Ethereum",
  "Binance Smart Chain",
  "IPFS",
  "Smart Contracts",
  "DeFi",
  "NFTs",
  "DAOs",
  "Subgraphs (The Graph)",
  "Chainlink",

  // Databases & Data Engineering
  "SQL",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Microsoft SQL Server",
  "NoSQL",
  "MongoDB",
  "Redis",
  "Cassandra",
  "Firebase",
  "Prisma",
  "TypeORM",
  "Data Warehousing",
  "ETL",
  "Apache Spark",
  "Apache Kafka",
  "Hadoop",
  "Airflow",

  // AI & Machine Learning
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Python (AI)",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Keras",
  "Pandas",
  "NumPy",
  "Jupyter Notebooks",
  "Hugging Face",
  "OpenAI API",
  "LangChain",
  "Generative AI",
  "Prompt Engineering",

  // DevOps & Cloud
  "AWS",
  "Google Cloud Platform (GCP)",
  "Microsoft Azure",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Jenkins",
  "GitHub Actions",
  "Terraform",
  "Ansible",
  "Linux System Administration",
  "Bash Scripting",
  "Serverless",
  "Microservices",

  // Design & UI/UX
  "UI Design",
  "UX Design",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "User Research",
  "Wireframing",
  "Prototyping",
  "Design Systems",
  "Interaction Design",
  "Motion Design",
  "After Effects",
  "Blender",
  "3D Modeling",

  // Project Management & Business
  "Agile",
  "Scrum",
  "Kanban",
  "Jira",
  "Trello",
  "Asana",
  "Product Management",
  "Business Analysis",
  "Market Research",
  "Financial Modeling",
  "Data Analysis",
  "SQL (Analytics)",
  "Tableau",
  "Power BI",
  "Excel",

  // Writing & Content
  "Content Writing",
  "Copywriting",
  "Technical Writing",
  "SEO",
  "Blogging",
  "Content Strategy",
  "Social Media Marketing",
  "Email Marketing",
  "Grant Writing",
  "Editing",
  "Proofreading",

  // Marketing & Sales
  "Digital Marketing",
  "SEO Strategy",
  "SEM",
  "PPC",
  "Google Analytics",
  "Facebook Ads",
  "Instagram Marketing",
  "Lead Generation",
  "Salesforce",
  "HubSpot",
  "CRM Management",

  // Other Technical Skills
  "Cybersecurity",
  "Penetration Testing",
  "Network Security",
  "Git",
  "GitHub",
  "GitLab",
  "API Integration",
  "Software Testing",
  "QA",
  "Jest",
  "Cypress",
  "Playwright",
  "Selenium",

  // Soft Skills (for context)
  "Communication",
  "Teamwork",
  "Problem Solving",
  "Leadership",
  "Time Management",
  "Adaptability",
  "Creativity",
  "Critical Thinking",

  // More niche/specific skills
  "Game Development",
  "Unity",
  "Unreal Engine",
  "C++",
  "AR/VR Development",
  "Webflow",
  "Shopify",
  "Embedded Systems",
  "IoT",
  "MATLAB",
  "R",
  "Statistical Analysis",
  "Algorithmic Trading",
  "Quantum Computing",
  "Bioinformatics",
  "Sales Funnel Optimization",
  "Customer Support",
  "Zendesk",
  "Intercom",
  "Video Editing",
  "Adobe Premiere Pro",
  "Final Cut Pro",
  "Audio Production",
  "Logic Pro X",
  "Ableton Live",
  "Podcast Editing",
  "Illustration",
  "Procreate",
  "Voice Acting",
  "Translation",
  "Legal Writing",
  "E-commerce Management",
  "Dropshipping",
  "Amazon FBA",
];
