/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 *
 * (Manual override applied to align with custom Meritbase deployment.)
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    FreelancerRegistry: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialOwner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "wallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "profileCid",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "cvHash",
              type: "bytes32",
            },
          ],
          name: "FreelancerRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "wallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "profileCid",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "cvHash",
              type: "bytes32",
            },
          ],
          name: "FreelancerUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "wallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "status",
              type: "uint8",
            },
          ],
          name: "FreelancerVerificationChanged",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "fullName",
              type: "string",
            },
            {
              internalType: "string",
              name: "email",
              type: "string",
            },
            {
              internalType: "string",
              name: "phone",
              type: "string",
            },
            {
              internalType: "string",
              name: "profileCid",
              type: "string",
            },
            {
              internalType: "string",
              name: "govIdCid",
              type: "string",
            },
            {
              internalType: "bytes32",
              name: "cvHash",
              type: "bytes32",
            },
          ],
          name: "registerFreelancer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "profileCid",
              type: "string",
            },
            {
              internalType: "bytes32",
              name: "cvHash",
              type: "bytes32",
            },
          ],
          name: "updateFreelancer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "wallet",
              type: "address",
            },
            {
              internalType: "uint8",
              name: "status",
              type: "uint8",
            },
          ],
          name: "setVerificationStatus",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "wallet",
              type: "address",
            },
          ],
          name: "getFreelancer",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "wallet",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "fullName",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "email",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "phone",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "profileCid",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "govIdCid",
                  type: "string",
                },
                {
                  internalType: "bytes32",
                  name: "cvHash",
                  type: "bytes32",
                },
                {
                  internalType: "uint8",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "updatedAt",
                  type: "uint256",
                },
              ],
              internalType: "struct FreelancerRegistry.Freelancer",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "wallet",
              type: "address",
            },
          ],
          name: "isApproved",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 0,
    },
    EmployerRegistry: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialOwner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "wallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "companyName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "licenseCid",
              type: "string",
            },
          ],
          name: "EmployerRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "wallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "companyName",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "licenseCid",
              type: "string",
            },
          ],
          name: "EmployerUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",\n              name: "wallet",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "status",
              type: "uint8",
            },
          ],
          name: "EmployerVerificationChanged",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "companyName",
              type: "string",
            },
            {
              internalType: "string",
              name: "contactEmail",
              type: "string",
            },
            {
              internalType: "string",
              name: "licenseCid",
              type: "string",
            },
          ],
          name: "registerEmployer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "companyName",
              type: "string",
            },
            {
              internalType: "string",
              name: "licenseCid",
              type: "string",
            },
          ],
          name: "updateEmployer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "wallet",
              type: "address",
            },
            {
              internalType: "uint8",
              name: "status",
              type: "uint8",
            },
          ],
          name: "setVerificationStatus",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "wallet",
              type: "address",
            },
          ],
          name: "getEmployer",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "wallet",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "companyName",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "contactEmail",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "licenseCid",
                  type: "string",
                },
                {
                  internalType: "uint8",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "updatedAt",
                  type: "uint256",
                },
              ],
              internalType: "struct EmployerRegistry.Employer",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "wallet",
              type: "address",
            },
          ],
          name: "isApproved",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 0,
    },
    JobContract: {
      address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialOwner",
              type: "address",
            },
            {
              internalType: "address",
              name: "_freelancerRegistry",
              type: "address",
            },
            {
              internalType: "address",
              name: "_employerRegistry",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "EmployerNotVerified",
          type: "error",
        },
        {
          inputs: [],
          name: "FreelancerNotVerified",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidApplication",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidJob",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidScore",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidStatusTransition",
          type: "error",
        },
        {
          inputs: [],
          name: "JobNotOpen",
          type: "error",
        },
        {
          inputs: [],
          name: "NotJobOwner",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "employer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint16",
              name: "openings",
              type: "uint16",
            },
          ],
          name: "JobCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "status",
              type: "uint8",
            },
          ],
          name: "JobStatusChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "proposalCid",
              type: "string",
            },
          ],
          name: "ApplicationSubmitted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "status",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint96",
              name: "matchScore",
              type: "uint96",
            },
          ],
          name: "ApplicationStatusUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "rating",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reviewCid",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "badgeCid",
              type: "string",
            },
          ],
          name: "GigReviewRecorded",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "title",
              type: "string",
            },
            {
              internalType: "string",
              name: "descriptionCid",
              type: "string",
            },
            {
              internalType: "string",
              name: "requirementsCid",
              type: "string",
            },
            {
              internalType: "uint16",
              name: "openings",
              type: "uint16",
            },
          ],
          name: "createJob",
          outputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "status",
              type: "uint8",
            },
          ],
          name: "updateJobStatus",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "proposalCid",
              type: "string",
            },
          ],
          name: "applyToJob",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
          ],
          name: "withdrawApplication",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              internalType: "address[]",
              name: "shortlisted",
              type: "address[]",
            },
            {
              internalType: "uint96[]",
              name: "scores",
              type: "uint96[]",
            },
          ],
          name: "recordShortlist",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              internalType: "address[]",
              name: "accepted",
              type: "address[]",
            },
          ],
          name: "recordFinalSelection",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              internalType: "address[]",
              name: "rejected",
              type: "address[]",
            },
          ],
          name: "recordRejection",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
            {
              internalType: "uint8",
              name: "rating",
              type: "uint8",
            },
            {
              internalType: "string",
              name: "reviewCid",
              type: "string",
            },
            {
              internalType: "string",
              name: "badgeCid",
              type: "string",
            },
          ],
          name: "recordGigReview",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
          ],
          name: "cancelJob",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
          ],
          name: "getJob",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "employer",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "title",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "descriptionCid",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "requirementsCid",
                  type: "string",
                },
                {
                  internalType: "uint16",
                  name: "openings",
                  type: "uint16",
                },
                {
                  internalType: "uint256",
                  name: "createdAt",
                  type: "uint256",
                },
                {
                  internalType: "uint8",
                  name: "status",
                  type: "uint8",
                },
              ],
              internalType: "struct JobContract.Job",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
          ],
          name: "getJobApplicants",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "jobId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
          ],
          name: "getApplication",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "freelancer",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "proposalCid",
                  type: "string",
                },
                {
                  internalType: "uint8",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "uint96",
                  name: "matchScore",
                  type: "uint96",
                },
                {
                  internalType: "uint256",
                  name: "updatedAt",
                  type: "uint256",
                },
              ],
              internalType: "struct JobContract.Application",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "freelancer",
              type: "address",
            },
          ],
          name: "getFreelancerReputation",
          outputs: [
            {
              components: [
                {
                  internalType: "uint64",
                  name: "cumulativeRating",
                  type: "uint64",
                },
                {
                  internalType: "uint32",
                  name: "ratingCount",
                  type: "uint32",
                },
                {
                  internalType: "uint32",
                  name: "gigsCompleted",
                  type: "uint32",
                },
                {
                  internalType: "string[]",
                  name: "badgeCids",
                  type: "string[]",
                },
              ],
              internalType: "struct JobContract.Reputation",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 0,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;